name: main

on:
  push:
    branches:
    tags:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Go-Linty
      uses: ArangoGutierrez/GoLinty-Action@go-1.13rc1-alpine
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    - name: Shell Linter
      uses: azohra/shell-linter@v0.2.0
