name: main

on:
  push:
    branches:
    tags:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Run GolangCI-Lint Action by building from repository
      uses: matoous/golangci-lint-action@v1.23.3
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
