name: main

on:
  push:
    branches:
    tags:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Shell Linter
      uses: azohra/shell-linter@v0.2.0
    - name: Go-Linty
      uses: ArangoGutierrez/GoLinty-Action@go-1.13rc1-alpine
