name: main

on:
  push:
    branches:
    tags:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: golangci-lint
      uses: actions-contrib/golangci-lint@v1
    - name: GolangCI-Linter
      uses: Mushus/golangci-linter@v1.1.2
