name: main

on:
  push:
    branches:
    tags:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Lint Action
      uses: samuelmeuli/lint-action@v1.2.0
      with:
        github_token: ${{ secrets.LINT_GH_TOKEN }}
        auto_fix: n
        gofmt: y
        golint: y
